drop view if exists nj.report_summary_wide; 
create view nj.report_summary_wide as 
with 
crash as (select 
c.casenumber,
c."year" as crash_year,
count(*) filter (where c.crash_type = '00' or c.crash_type is null) as ct_unknown,
count(*) filter (where c.crash_type = '01') as ct_same_direction_rearend,
count(*) filter (where c.crash_type = '02') as ct_same_direction_sideswipe,
count(*) filter (where c.crash_type = '03') as ct_right_angle,
count(*) filter (where c.crash_type = '04') as ct_opposite_direction_headon_angular,
count(*) filter (where c.crash_type = '05') as ct_opposite_direction_sideswipe,
count(*) filter (where c.crash_type = '06') as ct_struck_parked_vehicle,
count(*) filter (where c.crash_type = '07') as ct_left_turn_u_turn,
count(*) filter (where c.crash_type = '08') as ct_backing,
count(*) filter (where c.crash_type = '09') as ct_encroachment,
count(*) filter (where c.crash_type = '10') as ct_overturned,
count(*) filter (where c.crash_type = '11') as ct_fixed_object,
count(*) filter (where c.crash_type = '12') as ct_animal,
count(*) filter (where c.crash_type = '13') as ct_pedestrian,
count(*) filter (where c.crash_type = '14') as ct_pedalcyclist,
count(*) filter (where c.crash_type = '15') as ct_non_fixed_object,
count(*) filter (where c.crash_type = '16') as ct_railcar_vehicle,
count(*) filter (where c.crash_type = '99') as ct_other,
count(*) filter (where c.severity = 'P') AS inj_no_injury,
count(*) filter (where c.severity = 'F') AS inj_fatal,
count(*) filter (where c.severity = 'I') AS inj_injury,
count(*) filter (where c.severity = '9' or c.severity is null) AS inj_unknown,
count(*) filter (where c.road_surface_condition = '00' or c.road_surface_condition is null) AS road_unknown,
count(*) filter (where c.road_surface_condition = '01') AS road_dry,
count(*) filter (where c.road_surface_condition = '02') AS road_wet,
count(*) filter (where c.road_surface_condition = '03') AS road_snow,
count(*) filter (where c.road_surface_condition = '04') AS road_icy,
count(*) filter (where c.road_surface_condition IN ('05', '06', '07', '08', '09', '99')) AS road_other,
count(*) filter (where c.environmental_condition = '00' or c.environmental_condition is null) AS weather_unknown,
count(*) filter (where c.environmental_condition = '01') AS weather_clear,
count(*) filter (where c.environmental_condition = '02') AS weather_rain,
count(*) filter (where c.environmental_condition = '03') AS weather_snow,
count(*) filter (where c.environmental_condition IN ('04', '05', '06', '07', '08', '09', '10', '99')) AS weather_other,
count(*) filter (where c.light_condition = '00' or c.light_condition is null) AS ill_unknown,
count(*) filter (where c.light_condition = '01') AS ill_daylight,
count(*) filter (where c.light_condition = '02') AS ill_dawn,
count(*) filter (where c.light_condition = '03') AS ill_dusk,
count(*) filter (where c.light_condition = '04') AS ill_dark_street_lights_off,
count(*) filter (where c.light_condition = '05') AS ill_dark_no_street_lights,
count(*) filter (where c.light_condition = '06') AS ill_dark_streetlight_continuous,
count(*) filter (where c.light_condition = '07') AS ill_dark_streetlight_spot,
count(*) filter (where c.light_condition in ('99')) AS ill_other,
count(*) filter (where cast(extract(month from c."date") as text) = '01') as month_jan,
count(*) filter (where cast(extract(month from c."date") as text) = '02') as month_feb,
count(*) filter (where cast(extract(month from c."date") as text) = '03') as month_mar,
count(*) filter (where cast(extract(month from c."date") as text) = '04') as month_apr,
count(*) filter (where cast(extract(month from c."date") as text) = '05') as month_may,
count(*) filter (where cast(extract(month from c."date") as text) = '06') as month_jun,
count(*) filter (where cast(extract(month from c."date") as text) = '07') as month_jul,
count(*) filter (where cast(extract(month from c."date") as text) = '08') as month_aug,
count(*) filter (where cast(extract(month from c."date") as text) = '09') as month_sep,
count(*) filter (where cast(extract(month from c."date") as text) = '10') as month_oct,
count(*) filter (where cast(extract(month from c."date") as text) = '11') as month_nov,
count(*) filter (where cast(extract(month from c."date") as text) = '12') as month_dec,
count(*) filter (where c.day_of_week = '1') as day_sun,
count(*) filter (where c.day_of_week = '2') as day_mon,
count(*) filter (where c.day_of_week = '3') as day_tue,
count(*) filter (where c.day_of_week = '4') as day_wed,
count(*) filter (where c.day_of_week = '5') as day_thu,
count(*) filter (where c.day_of_week = '6') as day_fri,
count(*) filter (where c.day_of_week = '7') as day_sat,
count(*) filter (where c.time_of_day = '00') as hour_00,
count(*) filter (where c.time_of_day = '01') as hour_01,
count(*) filter (where c.time_of_day = '02') as hour_02,
count(*) filter (where c.time_of_day = '03') as hour_03,
count(*) filter (where c.time_of_day = '04') as hour_04,
count(*) filter (where c.time_of_day = '05') as hour_05,
count(*) filter (where c.time_of_day = '06') as hour_06,
count(*) filter (where c.time_of_day = '07') as hour_07,
count(*) filter (where c.time_of_day = '08') as hour_08,
count(*) filter (where c.time_of_day = '09') as hour_09,
count(*) filter (where c.time_of_day = '10') as hour_10,
count(*) filter (where c.time_of_day = '11') as hour_11,
count(*) filter (where c.time_of_day = '12') as hour_12,
count(*) filter (where c.time_of_day = '13') as hour_13,
count(*) filter (where c.time_of_day = '14') as hour_14,
count(*) filter (where c.time_of_day = '15') as hour_15,
count(*) filter (where c.time_of_day = '16') as hour_16,
count(*) filter (where c.time_of_day = '17') as hour_17,
count(*) filter (where c.time_of_day = '18') as hour_18,
count(*) filter (where c.time_of_day = '19') as hour_19,
count(*) filter (where c.time_of_day = '20') as hour_20,
count(*) filter (where c.time_of_day = '21') as hour_21,
count(*) filter (where c.time_of_day = '22') as hour_22,
count(*) filter (where c.time_of_day = '23') as hour_23
from nj.all_crash c
group by c.casenumber, crash_year), 
vehicle as (select
casenumber,
count(*) filter (where veh_type = '00' or veh_type is null) as veh_unknown,
count(*) filter (where veh_type = '01') as veh_car_stationwagon_minivan,
count(*) filter (where veh_type = '08') as veh_motorcycle,
count(*) filter (where veh_type = '05') as veh_smalltruck,
count(*) filter (where veh_type in ('20', '21', '22', '23', '24', '25', '26', '27', '29')) as veh_largetruck,
count(*) filter (where veh_type in ('02', '03', '04', '06', '07', '10', '15', '16', '19', '30', '31', '40', '99')) as veh_other_motor,
count(*) filter (where veh_type in ('12', '14')) as veh_other_nonmotor,
count(*) filter (where veh_type = '13') as veh_bicycle
from nj.all_vehicle
group by casenumber), 
person as (select 
casenumber,
count(*) filter (where physical_condition = '00' or physical_condition is null) as person_unknown,
count(*) filter (where physical_condition = '01') as person_fatal,
count(*) filter (where physical_condition = '02') as person_serious,
count(*) filter (where physical_condition = '03') as person_minor,
count(*) filter (where physical_condition = '04') as person_possible,
count(*) filter (where physical_condition = '05') as person_no_injury,
count(*) filter (where physical_condition = '99' or physical_condition is null) as person_other
from nj.all_person 
group by casenumber
)


select 
c.*, 
v.veh_unknown,
v.veh_car_stationwagon_minivan,
v.veh_motorcycle, 
v.veh_smalltruck, 
v.veh_largetruck, 
v.veh_other_motor, 
v.veh_other_nonmotor, 
v.veh_bicycle, 
p.person_unknown,
p.person_fatal, 
p.person_serious, 
p.person_minor, 
p.person_possible, 
p.person_no_injury, 
p.person_other
from crash c 
left join vehicle v 
on c.casenumber = v.casenumber 
left join person p
on c.casenumber = p.casenumber;