drop view if exists pa.report_summary_wide; 
create view pa.report_summary_wide as 
with 
crash as (select 
c.crn,
c.crash_year,
count(*) filter (where c.collision_type = '0') as ct_noncollision,
count(*) filter (where c.collision_type = '1') as ct_rearend,
count(*) filter (where c.collision_type = '2') as ct_headon,
count(*) filter (where c.collision_type = '3') as ct_backing,
count(*) filter (where c.collision_type = '4') as ct_angle,
count(*) filter (where c.collision_type = '5') as ct_sideswipe_same,
count(*) filter (where c.collision_type = '6') as ct_sideswipe_opp,
count(*) filter (where c.collision_type = '7') as ct_hitfixedobject,
count(*) filter (where c.collision_type = '8') as ct_hitnonmotorist,
count(*) filter (where c.collision_type in ('9', '98', '99') or c.collision_type is null) as ct_other_unknown,
count(*) filter (where c.max_severity_level = '0') AS inj_noinjury,
count(*) filter (where c.max_severity_level = '1') AS inj_fatal,
count(*) filter (where c.max_severity_level = '2') AS inj_serious,
count(*) filter (where c.max_severity_level = '3') AS inj_minor,
count(*) filter (where c.max_severity_level = '4') AS inj_possible,
count(*) filter (where c.max_severity_level = '8') AS inj_inj_unknown,
count(*) filter (where c.max_severity_level = '9' or c.max_severity_level is null) AS inj_unknown,
count(*) filter (where c.road_condition = '01') AS road_dry,
count(*) filter (where c.road_condition = '02') AS road_ice,
count(*) filter (where c.road_condition = '07') AS road_snow,
count(*) filter (where c.road_condition = '08') AS road_water,
count(*) filter (where c.road_condition = '09') AS road_wet,
count(*) filter (where c.road_condition IN ('03', '04', '05', '06', '22', '98')) AS road_other,
count(*) filter (where c.road_condition = '99' or c.road_condition is null) AS road_unknown,
count(*) filter (where c.weather1 = '03') AS weather_clear,
count(*) filter (where c.weather1 = '04') AS weather_cloudy,
count(*) filter (where c.weather1 = '05') AS weather_fogsmogsmoke,
count(*) filter (where c.weather1 = '07') AS weather_rain,
count(*) filter (where c.weather1 = '10') AS weather_snow,
count(*) filter (where c.weather1 IN ('01', '02', '06', '08', '09', '98')) AS weather_other,
count(*) filter (where c.weather1 = '99' or c.weather1 is null) AS weather_unknown,
count(*) filter (where c.illumination = '1') AS ill_daylight,
count(*) filter (where c.illumination = '2') AS ill_dark_nostreet,
count(*) filter (where c.illumination = '3') AS ill_dark_street,
count(*) filter (where c.illumination = '4') AS ill_dusk,
count(*) filter (where c.illumination = '5') AS ill_dawn,
count(*) filter (where c.illumination in ('6', '8')) AS ill_other,
count(*) filter (where c.illumination = '9' or c.illumination is null) AS ill_unknown,
count(*) filter (where c.crash_month = '01') as month_jan,
count(*) filter (where c.crash_month = '02') as month_feb,
count(*) filter (where c.crash_month = '03') as month_mar,
count(*) filter (where c.crash_month = '04') as month_apr,
count(*) filter (where c.crash_month = '05') as month_may,
count(*) filter (where c.crash_month = '06') as month_jun,
count(*) filter (where c.crash_month = '07') as month_jul,
count(*) filter (where c.crash_month = '08') as month_aug,
count(*) filter (where c.crash_month = '09') as month_sep,
count(*) filter (where c.crash_month = '10') as month_oct,
count(*) filter (where c.crash_month = '11') as month_nov,
count(*) filter (where c.crash_month = '12') as month_dec,
count(*) filter (where c.day_of_week = '1') as day_sun,
count(*) filter (where c.day_of_week = '2') as day_mon,
count(*) filter (where c.day_of_week = '3') as day_tue,
count(*) filter (where c.day_of_week = '4') as day_wed,
count(*) filter (where c.day_of_week = '5') as day_thu,
count(*) filter (where c.day_of_week = '6') as day_fri,
count(*) filter (where c.day_of_week = '7') as day_sat,
count(*) filter (where c.hour_of_day = '00') as hour_00,
count(*) filter (where c.hour_of_day = '01') as hour_01,
count(*) filter (where c.hour_of_day = '02') as hour_02,
count(*) filter (where c.hour_of_day = '03') as hour_03,
count(*) filter (where c.hour_of_day = '04') as hour_04,
count(*) filter (where c.hour_of_day = '05') as hour_05,
count(*) filter (where c.hour_of_day = '06') as hour_06,
count(*) filter (where c.hour_of_day = '07') as hour_07,
count(*) filter (where c.hour_of_day = '08') as hour_08,
count(*) filter (where c.hour_of_day = '09') as hour_09,
count(*) filter (where c.hour_of_day = '10') as hour_10,
count(*) filter (where c.hour_of_day = '11') as hour_11,
count(*) filter (where c.hour_of_day = '12') as hour_12,
count(*) filter (where c.hour_of_day = '13') as hour_13,
count(*) filter (where c.hour_of_day = '14') as hour_14,
count(*) filter (where c.hour_of_day = '15') as hour_15,
count(*) filter (where c.hour_of_day = '16') as hour_16,
count(*) filter (where c.hour_of_day = '17') as hour_17,
count(*) filter (where c.hour_of_day = '18') as hour_18,
count(*) filter (where c.hour_of_day = '19') as hour_19,
count(*) filter (where c.hour_of_day = '20') as hour_20,
count(*) filter (where c.hour_of_day = '21') as hour_21,
count(*) filter (where c.hour_of_day = '22') as hour_22,
count(*) filter (where c.hour_of_day = '23') as hour_23
from pa.all_crash c
group by c.crn, c.crash_year), 
vehicle as (select
crn,
count(*) filter (where veh_type = '01') as veh_automobile,
count(*) filter (where veh_type = '02') as veh_motorcycle,
count(*) filter (where veh_type = '03') as veh_bus,
count(*) filter (where veh_type = '04') as veh_smalltruck,
count(*) filter (where veh_type = '05') as veh_bigtruck,
count(*) filter (where veh_type in ('06', '07', '08', '09', '10', '11', '12', '13', '14', '15' ,'16' ,'17', '18', '19')) as veh_othermotorvehicle,
count(*) filter (where veh_type = '20') as veh_bicycle,
count(*) filter (where veh_type = '31') as veh_pedestrian,
count(*) filter (where veh_type in ('21', '22', '23', '24', '25', '32', '33', '34', '35', '36', '98')) as veh_othernonmotor,
count(*) filter (where veh_type = '99' or veh_type is null) as veh_unknown
from pa.all_vehicle
group by crn), 
person as (select 
crn,
count(*) filter (where inj_severity = '0') as person_notinjured,
count(*) filter (where inj_severity = '1') as person_fatal,
count(*) filter (where inj_severity = '2') as person_serious,
count(*) filter (where inj_severity = '3') as person_minor,
count(*) filter (where inj_severity = '4') as person_possible,
count(*) filter (where inj_severity = '8') as person_injuryunknown,
count(*) filter (where inj_severity = '9' or inj_severity is null) as person_unknown
from pa.all_person 
group by crn
)


select 
c.*, 
v.veh_automobile,
v.veh_motorcycle,
v.veh_bus, 
v.veh_smalltruck, 
v.veh_bigtruck, 
v.veh_othermotorvehicle, 
v.veh_bicycle, 
v.veh_pedestrian, 
v.veh_othernonmotor, 
v.veh_unknown,
p.person_notinjured,
p.person_fatal, 
p.person_serious, 
p.person_minor, 
p.person_possible, 
p.person_injuryunknown, 
p.person_unknown
from crash c 
left join vehicle v 
on c.crn = v.crn 
left join person p
on c.crn = p.crn;