crash_cols = [
    "CRN",
    "ARRIVAL_TM",
    "AUTOMOBILE_COUNT",
    "BELTED_DEATH_COUNT",
    "BELTED_SUSP_SERIOUS_INJ_COUNT",
    "BICYCLE_COUNT",
    "BICYCLE_DEATH_COUNT",
    "BICYCLE_SUSP_SERIOUS_INJ_COUNT",
    "BUS_COUNT",
    "CHLDPAS_DEATH_COUNT",
    "CHLDPAS_SUSP_SERIOUS_INJ_COUNT",
    "COLLISION_TYPE",
    "COMM_VEH_COUNT",
    "CONS_ZONE_SPD_LIM",
    "COUNTY",
    "CRASH_MONTH",
    "CRASH_YEAR",
    "DAY_OF_WEEK",
    "DEC_LAT",
    "DEC_LONG",
    "DISPATCH_TM",
    "DISTRICT",
    "DRIVER_COUNT_16YR",
    "DRIVER_COUNT_17YR",
    "DRIVER_COUNT_18YR",
    "DRIVER_COUNT_19YR",
    "DRIVER_COUNT_20YR",
    "DRIVER_COUNT_50_64YR",
    "DRIVER_COUNT_65_74YR",
    "DRIVER_COUNT_75PLUS",
    "EST_HRS_CLOSED",
    "FATAL_COUNT",
    "HEAVY_TRUCK_COUNT",
    "HORSE_BUGGY_COUNT",
    "HOUR_OF_DAY",
    "ILLUMINATION",
    "INJURY_COUNT",
    "INTERSECTION_RELATED",
    "INTERSECT_TYPE",
    "LANE_CLOSED",
    "LATITUDE",
    "LN_CLOSE_DIR",
    "LOCATION_TYPE",
    "LONGITUDE",
    "MAX_SEVERITY_LEVEL",
    "MCYCLE_DEATH_COUNT",
    "MCYCLE_SUSP_SERIOUS_INJ_COUNT",
    "MOTORCYCLE_COUNT",
    "MUNICIPALITY",
    "NONMOTR_COUNT",
    "NONMOTR_DEATH_COUNT",
    "NONMOTR_SUSP_SERIOUS_INJ_COUNT",
    "NTFY_HIWY_MAINT",
    "PED_COUNT",
    "PED_DEATH_COUNT",
    "PED_SUSP_SERIOUS_INJ_COUNT",
    "PERSON_COUNT",
    "POLICE_AGCY",
    "POSSIBLE_INJ_COUNT",
    "RDWY_SURF_TYPE_CD",
    "RELATION_TO_ROAD",
    "ROADWAY_CLEARED",
    "ROAD_CONDITION",
    "SCH_BUS_IND",
    "SCH_ZONE_IND",
    "SECONDARY_CRASH",
    "SMALL_TRUCK_COUNT",
    "SPEC_JURIS_CD",
    "SUSP_MINOR_INJ_COUNT",
    "SUSP_SERIOUS_INJ_COUNT",
    "SUV_COUNT",
    "TCD_FUNC_CD",
    "TCD_TYPE",
    "TFC_DETOUR_IND",
    "TIME_OF_DAY",
    "TOTAL_UNITS",
    "TOT_INJ_COUNT",
    "UNBELTED_OCC_COUNT",
    "UNB_DEATH_COUNT",
    "UNB_SUSP_SERIOUS_INJ_COUNT",
    "UNK_INJ_DEG_COUNT",
    "UNK_INJ_PER_COUNT",
    "URBAN_RURAL",
    "VAN_COUNT",
    "VEHICLE_COUNT",
    "WEATHER1",
    "WEATHER2",
    "WORKERS_PRES",
    "WORK_ZONE_IND",
    "WORK_ZONE_LOC",
    "WORK_ZONE_TYPE",
    "WZ_CLOSE_DETOUR",
    "WZ_FLAGGER",
    "WZ_LAW_OFFCR_IND",
    "WZ_LN_CLOSURE",
    "WZ_MOVING",
    "WZ_OTHER",
    "WZ_SHLDER_MDN",
    "WZ_WORKERS_INJ_KILLED",
]

crash_dict = {
    "CRN": int,
    "ARRIVAL_TM": str,
    "AUTOMOBILE_COUNT": float,
    "BELTED_DEATH_COUNT": float,
    "BELTED_SUSP_SERIOUS_INJ_COUNT": float,
    "BICYCLE_COUNT": float,
    "BICYCLE_DEATH_COUNT": float,
    "BICYCLE_SUSP_SERIOUS_INJ_COUNT": float,
    "BUS_COUNT": float,
    "CHLDPAS_DEATH_COUNT": float,
    "CHLDPAS_SUSP_SERIOUS_INJ_COUNT": float,
    "COLLISION_TYPE": str,
    "COMM_VEH_COUNT": float,
    "CONS_ZONE_SPD_LIM": str,
    "COUNTY": str,
    "CRASH_MONTH": str,
    "CRASH_YEAR": str,
    "DAY_OF_WEEK": str,
    "DEC_LAT": float,
    "DEC_LONG": float,
    "DISPATCH_TM": str,
    "DISTRICT": str,
    "DRIVER_COUNT_16YR": float,
    "DRIVER_COUNT_17YR": float,
    "DRIVER_COUNT_18YR": float,
    "DRIVER_COUNT_19YR": float,
    "DRIVER_COUNT_20YR": float,
    "DRIVER_COUNT_50_64YR": float,
    "DRIVER_COUNT_65_74YR": float,
    "DRIVER_COUNT_75PLUS": float,
    "EST_HRS_CLOSED": str,
    "FATAL_COUNT": float,
    "HEAVY_TRUCK_COUNT": float,
    "HORSE_BUGGY_COUNT": float,
    "HOUR_OF_DAY": str,
    "ILLUMINATION": str,
    "INJURY_COUNT": float,
    "INTERSECTION_RELATED": str,
    "INTERSECT_TYPE": str,
    "LANE_CLOSED": str,
    "LATITUDE": str,
    "LN_CLOSE_DIR": str,
    "LOCATION_TYPE": str,
    "LONGITUDE": str,
    "MAX_SEVERITY_LEVEL": str,
    "MCYCLE_DEATH_COUNT": float,
    "MCYCLE_SUSP_SERIOUS_INJ_COUNT": float,
    "MOTORCYCLE_COUNT": float,
    "MUNICIPALITY": str,
    "NONMOTR_COUNT": float,
    "NONMOTR_DEATH_COUNT": float,
    "NONMOTR_SUSP_SERIOUS_INJ_COUNT": float,
    "NTFY_HIWY_MAINT": str,
    "PED_COUNT": float,
    "PED_DEATH_COUNT": float,
    "PED_SUSP_SERIOUS_INJ_COUNT": float,
    "PERSON_COUNT": float,
    "POLICE_AGCY": str,
    "POSSIBLE_INJ_COUNT": float,
    "RDWY_SURF_TYPE_CD": str,
    "RELATION_TO_ROAD": str,
    "ROADWAY_CLEARED": str,
    "ROAD_CONDITION": str,
    "SCH_BUS_IND": str,
    "SCH_ZONE_IND": str,
    "SECONDARY_CRASH": str,
    "SMALL_TRUCK_COUNT": float,
    "SPEC_JURIS_CD": str,
    "SUSP_MINOR_INJ_COUNT": float,
    "SUSP_SERIOUS_INJ_COUNT": float,
    "SUV_COUNT": float,
    "TCD_FUNC_CD": str,
    "TCD_TYPE": str,
    "TFC_DETOUR_IND": str,
    "TIME_OF_DAY": str,
    "TOTAL_UNITS": float,
    "TOT_INJ_COUNT": float,
    "UNBELTED_OCC_COUNT": float,
    "UNB_DEATH_COUNT": float,
    "UNB_SUSP_SERIOUS_INJ_COUNT": float,
    "UNK_INJ_DEG_COUNT": float,
    "UNK_INJ_PER_COUNT": float,
    "URBAN_RURAL": str,
    "VAN_COUNT": float,
    "VEHICLE_COUNT": float,
    "WEATHER1": float,
    "WEATHER2": str,
    "WORKERS_PRES": str,
    "WORK_ZONE_IND": str,
    "WORK_ZONE_LOC": str,
    "WORK_ZONE_TYPE": str,
    "WZ_CLOSE_DETOUR": str,
    "WZ_FLAGGER": str,
    "WZ_LAW_OFFCR_IND": str,
    "WZ_LN_CLOSURE": str,
    "WZ_MOVING": str,
    "WZ_OTHER": str,
    "WZ_SHLDER_MDN": str,
    "WZ_WORKERS_INJ_KILLED": str,
}

commveh_cols = [
    "CRN",
    "CRASH_YEAR",
    "COUNTY",
    "AXLE_CNT",
    "CARGO_BD_TYPE",
    "CARRIER_ADDR1",
    "CARRIER_ADDR2",
    "CARRIER_CITY",
    "CARRIER_STATE",
    "CARRIER_ZIP",
    "CARRIER_NM",
    "CARRIER_TEL",
    "GVWR",
    "HAZMAT_CD1",
    "HAZMAT_CD2",
    "HAZMAT_CD3",
    "HAZMAT_CD4",
    "HAZMAT_IND",
    "HAZMAT_REL_IND1",
    "HAZMAT_REL_IND2",
    "HAZMAT_REL_IND3",
    "HAZMAT_REL_IND4",
    "ICC_NUM",
    "OSIZE_LOAD_IND",
    # "PARTIAL_TRAILER_VIN",
    "PERMITTED",
    "PUC_NUM",
    "SPECIAL_SIZING1",
    "SPECIAL_SIZING2",
    "SPECIAL_SIZING3",
    "SPECIAL_SIZING4",
    "TYPE_OF_CARRIER",
    "UNIT_NUM",
    "USDOT_NUM",
    "VEH_CONFIG_CD",
]

commveh_dict = {
    "CRN": int,
    "CRASH_YEAR": str,
    "COUNTY": str,
    "AXLE_CNT": str,
    "CARGO_BD_TYPE": str,
    "CARRIER_ADDR1": str,
    "CARRIER_ADDR2": str,
    "CARRIER_CITY": str,
    "CARRIER_STATE": str,
    "CARRIER_ZIP": str,
    "CARRIER_NM": str,
    "CARRIER_TEL": str,
    "GVWR": str,
    "HAZMAT_CD1": str,
    "HAZMAT_CD2": str,
    "HAZMAT_CD3": str,
    "HAZMAT_CD4": str,
    "HAZMAT_IND": str,
    "HAZMAT_REL_IND1": str,
    "HAZMAT_REL_IND2": str,
    "HAZMAT_REL_IND3": str,
    "HAZMAT_REL_IND4": str,
    "ICC_NUM": str,
    "OSIZE_LOAD_IND": str,
    # "PARTIAL_TRAILER_VIN": str,
    "PERMITTED": str,
    "PUC_NUM": str,
    "SPECIAL_SIZING1": str,
    "SPECIAL_SIZING2": str,
    "SPECIAL_SIZING3": str,
    "SPECIAL_SIZING4": str,
    "TYPE_OF_CARRIER": str,
    "UNIT_NUM": float,
    "USDOT_NUM": str,
    "VEH_CONFIG_CD": str,
}

cycle_cols = [
    "CRN",
    "CRASH_YEAR",
    "COUNTY",
    "MC_BAG_IND",
    "MC_DVR_BOOTS_IND",
    "MC_DVR_EDC_IND",
    "MC_DVR_EYEPRT_IND",
    "MC_DVR_HLMTDOT_IND",
    "MC_DVR_HLMTON_IND",
    "MC_DVR_HLMT_TYPE",
    "MC_DVR_LNGPNTS_IND",
    "MC_DVR_LNGSLV_IND",
    "MC_ENGINE_SIZE",
    "MC_PASSNGR_IND",
    "MC_PAS_BOOTS_IND",
    "MC_PAS_EYEPRT_IND",
    "MC_PAS_HLMTDOT_IND",
    "MC_PAS_HLMTON_IND",
    "MC_PAS_HLMT_TYPE",
    "MC_PAS_LNGPNTS_IND",
    "MC_PAS_LNGSLV_IND",
    "MC_TRAIL_IND",
    "UNIT_NUM",
]

cycle_dict = {
    "CRN": int,
    "CRASH_YEAR": str,
    "COUNTY": str,
    "MC_BAG_IND": str,
    "MC_DVR_BOOTS_IND": str,
    "MC_DVR_EDC_IND": str,
    "MC_DVR_EYEPRT_IND": str,
    "MC_DVR_HLMTDOT_IND": str,
    "MC_DVR_HLMTON_IND": str,
    "MC_DVR_HLMT_TYPE": str,
    "MC_DVR_LNGPNTS_IND": str,
    "MC_DVR_LNGSLV_IND": str,
    "MC_ENGINE_SIZE": str,
    "MC_PASSNGR_IND": str,
    "MC_PAS_BOOTS_IND": str,
    "MC_PAS_EYEPRT_IND": str,
    "MC_PAS_HLMTDOT_IND": str,
    "MC_PAS_HLMTON_IND": str,
    "MC_PAS_HLMT_TYPE": str,
    "MC_PAS_LNGPNTS_IND": str,
    "MC_PAS_LNGSLV_IND": str,
    "MC_TRAIL_IND": str,
    "UNIT_NUM": float,
}

flags_cols = [
    "CRN",
    "CRASH_YEAR",
    "COUNTY",
    "AGGRESSIVE_DRIVING",
    "ALCOHOL_RELATED",
    "ANGLE_CRASH",
    "ATV",
    "ATV_ROUTE",
    "BACKUP_CONGESTION",
    "BACKUP_NONRECURRING",
    "BACKUP_PRIOR",
    "BICYCLE",
    "CELL_PHONE",
    "CHILD_PASSENGER",
    "COMM_VEHICLE",
    "CORE_NETWORK",
    "CROSS_MEDIAN",
    "CURVED_ROAD",
    "CURVE_DVR_ERROR",
    "DEER_RELATED",
    "DISTRACTED",
    "DRINKING_DRIVER",
    "DRIVER_16YR",
    "DRIVER_17YR",
    "DRIVER_18YR",
    "DRIVER_19YR",
    "DRIVER_20YR",
    "DRIVER_50_64YR",
    "DRIVER_65_74YR",
    "DRIVER_75PLUS",
    "DRUGGED_DRIVER",
    "DRUG_RELATED",
    "FATAL",
    "FATAL_OR_SUSP_SERIOUS_INJ",
    "FATIGUE_ASLEEP",
    "FEDERAL_AID_ROUTE",
    "FIRE_IN_VEHICLE",
    "HAZARDOUS_TRUCK",
    "HIT_BARRIER",
    "HIT_BRIDGE",
    "HIT_DEER",
    "HIT_EMBANKMENT",
    "HIT_FIXED_OBJECT",
    "HIT_GDRAIL",
    "HIT_GDRAIL_END",
    "HIT_PARKED_VEHICLE",
    "HIT_POLE",
    "HIT_ROADWAY_EQUIPMENT",
    "HIT_RUN",
    "HIT_TEMP_CONSTRUCTION_BARRIER",
    "HIT_TRAFFIC_ISLAND",
    "HIT_TREE_SHRUB",
    "HIT_UTILITY_POLE",
    "HORSE_BUGGY",
    "HO_OPPDIR_SDSWP",
    "HVY_TRUCK_RELATED",
    "ICY_ROAD",
    "ILLEGAL_DRUG_RELATED",
    "ILLUMINATION_DARK",
    "IMPAIRED_DRIVER",
    "IMPAIRED_NONMOTORIST",
    "INJURY",
    "INJURY_OR_FATAL",
    "INTERSECTION",
    "INTERSECTION_RELATED",
    "INTERSTATE",
    "LANE_DEPARTURE",
    "LEFT_TURN",
    "LIMIT_65MPH",
    "LIMIT_70MPH",
    "LOCAL_ROAD",
    "LOCAL_ROAD_ONLY",
    "MARIJUANA_DRUGGED_DRIVER",
    "MARIJUANA_RELATED",
    "MATURE_DRIVER",
    "MC_DRINKING_DRIVER",
    "MOTORCYCLE",
    "MULTIPLE_VEHICLE",
    "NHTSA_AGG_DRIVING",
    "NON_INTERSECTION",
    "NO_CLEARANCE",
    "OPIOID_RELATED",
    "OTHER_FREEWAY",
    "OVERTURNED",
    "PEDESTRIAN",
    "PHANTOM_VEHICLE",
    "POSSIBLE_INJURY",
    "PROPERTY_DAMAGE_ONLY",
    "PSP_REPORTED",
    "RAMP",
    "RAMP_SEGMENT",
    "RAMP_TERMINAL",
    "REAR_END",
    "ROUNDABOUT",
    "RUNNING_RED_LT",
    "RUNNING_STOP_SIGN",
    "RURAL",
    "SCHOOL_BUS",
    "SCHOOL_BUS_RELATED",
    "SCHOOL_BUS_UNIT",
    "SCHOOL_ZONE",
    "SHLDR_RELATED",
    "SIGNALIZED_INT",
    "SINGLE_VEHICLE",
    "SNOWMOBILE",
    "SNOW_SLUSH_ROAD",
    "SPEEDING",
    "SPEEDING_RELATED",
    "SPEED_CHANGE_LANE",
    "STATE_ROAD",
    "STOP_CONTROLLED_INT",
    "SUDDEN_DEER",
    "SUSPECTED_MINOR_INJURY",
    "SUSPECTED_SERIOUS_INJURY",
    "SV_RUN_OFF_RD",
    "TAILGATING",
    "TRAIN",
    "TRAIN_TROLLEY",
    "TROLLEY",
    "TURNPIKE",
    "UNBELTED",
    "UNDERAGE_DRNK_DRV",
    "UNLICENSED",
    "UNSIGNALIZED_INT",
    "URBAN",
    "VEHICLE_FAILURE",
    "VEHICLE_TOWED",
    "VULNERABLE_ROADWAY_USER",
    "VULNERABLE_ROADWAY_USER_FATAL",
    "WET_ROAD",
    "WORK_ZONE",
    "YOUNG_DRIVER",
]


flags_dict = {
    "CRN": int,
    "CRASH_YEAR": str,
    "COUNTY": str,
    "AGGRESSIVE_DRIVING": float,
    "ALCOHOL_RELATED": float,
    "ANGLE_CRASH": float,
    "ATV": float,
    "ATV_ROUTE": float,
    "BACKUP_CONGESTION": float,
    "BACKUP_NONRECURRING": float,
    "BACKUP_PRIOR": float,
    "BICYCLE": float,
    "CELL_PHONE": float,
    "CHILD_PASSENGER": float,
    "COMM_VEHICLE": float,
    "CORE_NETWORK": float,
    "CROSS_MEDIAN": float,
    "CURVED_ROAD": float,
    "CURVE_DVR_ERROR": float,
    "DEER_RELATED": float,
    "DISTRACTED": float,
    "DRINKING_DRIVER": float,
    "DRIVER_16YR": float,
    "DRIVER_17YR": float,
    "DRIVER_18YR": float,
    "DRIVER_19YR": float,
    "DRIVER_20YR": float,
    "DRIVER_50_64YR": float,
    "DRIVER_65_74YR": float,
    "DRIVER_75PLUS": float,
    "DRUGGED_DRIVER": float,
    "DRUG_RELATED": float,
    "FATAL": float,
    "FATAL_OR_SUSP_SERIOUS_INJ": float,
    "FATIGUE_ASLEEP": float,
    "FEDERAL_AID_ROUTE": float,
    "FIRE_IN_VEHICLE": float,
    "HAZARDOUS_TRUCK": float,
    "HIT_BARRIER": float,
    "HIT_BRIDGE": float,
    "HIT_DEER": float,
    "HIT_EMBANKMENT": float,
    "HIT_FIXED_OBJECT": float,
    "HIT_GDRAIL": float,
    "HIT_GDRAIL_END": float,
    "HIT_PARKED_VEHICLE": float,
    "HIT_POLE": float,
    "HIT_ROADWAY_EQUIPMENT": float,
    "HIT_RUN": float,
    "HIT_TEMP_CONSTRUCTION_BARRIER": float,
    "HIT_TRAFFIC_ISLAND": float,
    "HIT_TREE_SHRUB": float,
    "HIT_UTILITY_POLE": float,
    "HORSE_BUGGY": float,
    "HO_OPPDIR_SDSWP": float,
    "HVY_TRUCK_RELATED": float,
    "ICY_ROAD": float,
    "ILLEGAL_DRUG_RELATED": float,
    "ILLUMINATION_DARK": float,
    "IMPAIRED_DRIVER": float,
    "IMPAIRED_NONMOTORIST": float,
    "INJURY": float,
    "INJURY_OR_FATAL": float,
    "INTERSECTION": float,
    "INTERSECTION_RELATED": float,
    "INTERSTATE": float,
    "LANE_DEPARTURE": float,
    "LEFT_TURN": float,
    "LIMIT_65MPH": float,
    "LIMIT_70MPH": float,
    "LOCAL_ROAD": float,
    "LOCAL_ROAD_ONLY": float,
    "MARIJUANA_DRUGGED_DRIVER": float,
    "MARIJUANA_RELATED": float,
    "MATURE_DRIVER": float,
    "MC_DRINKING_DRIVER": float,
    "MOTORCYCLE": float,
    "MULTIPLE_VEHICLE": float,
    "NHTSA_AGG_DRIVING": float,
    "NON_INTERSECTION": float,
    "NO_CLEARANCE": float,
    "OPIOID_RELATED": float,
    "OTHER_FREEWAY": float,
    "OVERTURNED": float,
    "PEDESTRIAN": float,
    "PHANTOM_VEHICLE": float,
    "POSSIBLE_INJURY": float,
    "PROPERTY_DAMAGE_ONLY": float,
    "PSP_REPORTED": float,
    "RAMP": float,
    "RAMP_SEGMENT": float,
    "RAMP_TERMINAL": float,
    "REAR_END": float,
    "ROUNDABOUT": float,
    "RUNNING_RED_LT": float,
    "RUNNING_STOP_SIGN": float,
    "RURAL": float,
    "SCHOOL_BUS": float,
    "SCHOOL_BUS_RELATED": float,
    "SCHOOL_BUS_UNIT": float,
    "SCHOOL_ZONE": float,
    "SHLDR_RELATED": float,
    "SIGNALIZED_INT": float,
    "SINGLE_VEHICLE": float,
    "SNOWMOBILE": float,
    "SNOW_SLUSH_ROAD": float,
    "SPEEDING": float,
    "SPEEDING_RELATED": float,
    "SPEED_CHANGE_LANE": float,
    "STATE_ROAD": float,
    "STOP_CONTROLLED_INT": float,
    "SUDDEN_DEER": float,
    "SUSPECTED_MINOR_INJURY": float,
    "SUSPECTED_SERIOUS_INJURY": float,
    "SV_RUN_OFF_RD": float,
    "TAILGATING": float,
    "TRAIN": float,
    "TRAIN_TROLLEY": float,
    "TROLLEY": float,
    "TURNPIKE": float,
    "UNBELTED": float,
    "UNDERAGE_DRNK_DRV": float,
    "UNLICENSED": float,
    "UNSIGNALIZED_INT": float,
    "URBAN": float,
    "VEHICLE_FAILURE": float,
    "VEHICLE_TOWED": float,
    "VULNERABLE_ROADWAY_USER": float,
    "VULNERABLE_ROADWAY_USER_FATAL": float,
    "WET_ROAD": float,
    "WORK_ZONE": float,
    "YOUNG_DRIVER": float,
}

person_cols = [
    "CRN",
    "CRASH_YEAR",
    "COUNTY",
    "AGE",
    "AIRBAG1",
    "AIRBAG2",
    "AIRBAG3",
    "AIRBAG4",
    "AIRBAG_PADS",
    "DVR_LIC_STATE",
    "DVR_PED_CONDITION",
    "EJECTION_IND",
    "EJECT_PATH_CD",
    "EXTRIC_IND",
    "INJ_SEVERITY",
    "NON_MOTORIST",
    "PERSON_NUM",
    "PERSON_TYPE",
    "RESTRAINT_HELMET",
    "SEAT_POSITION",
    "SEX",
    "TRANSPORTED",
    "TRANSPORTED_BY",
    "UNIT_NUM",
    "VULNERABLE_ROADWAY_USER",
]

person_dict = {
    "CRN": int,
    "CRASH_YEAR": str,
    "COUNTY": str,
    "AGE": float,
    "AIRBAG1": str,
    "AIRBAG2": str,
    "AIRBAG3": str,
    "AIRBAG4": str,
    "AIRBAG_PADS": str,
    "DVR_LIC_STATE": str,
    "DVR_PED_CONDITION": str,
    "EJECTION_IND": str,
    "EJECT_PATH_CD": str,
    "EXTRIC_IND": str,
    "INJ_SEVERITY": str,
    "NON_MOTORIST": str,
    "PERSON_NUM": float,
    "PERSON_TYPE": str,
    "RESTRAINT_HELMET": str,
    "SEAT_POSITION": str,
    "SEX": str,
    "TRANSPORTED": str,
    "TRANSPORTED_BY": str,
    "UNIT_NUM": float,
    "VULNERABLE_ROADWAY_USER": str,
}

roadway_cols = [
    "CRN",
    "CRASH_YEAR",
    "ACCESS_CTRL",
    "COUNTY",
    "LANE_COUNT",
    "OFFSET_FT",
    "RAMP",
    "RDWY_ORIENT",
    "RDWY_SEQ_NUM",
    "ROAD_OWNER",
    "ROUTE",
    "SEGMENT",
    "SPEED_LIMIT",
    "STREET_NAME",
]

roadway_dict = {
    "CRN": int,
    "CRASH_YEAR": str,
    "ACCESS_CTRL": str,
    "COUNTY": str,
    "LANE_COUNT": str,
    "OFFSET_FT": str,
    "RAMP": float,
    "RDWY_ORIENT": str,
    "RDWY_SEQ_NUM": float,
    "ROAD_OWNER": str,
    "ROUTE": str,
    "SEGMENT": str,
    "SPEED_LIMIT": str,
    "STREET_NAME": str,
}

trailveh_cols = [
    "CRN",
    "CRASH_YEAR",
    "COUNTY",
    "TRAILER_PARTIAL_VIN",
    "TRL_SEQ_NUM",
    "TRL_VEH_REG_STATE",
    "TRL_VEH_TAG_NUM",
    "TRL_VEH_TAG_YR",
    "TRL_VEH_TYPE_CD",
    "UNIT_NUM",
]

trailveh_dict = {
    "CRN": int,
    "CRASH_YEAR": str,
    "COUNTY": str,
    "TRAILER_PARTIAL_VIN": str,
    "TRL_SEQ_NUM": float,
    "TRL_VEH_REG_STATE": str,
    "TRL_VEH_TAG_NUM": str,
    "TRL_VEH_TAG_YR": str,
    "TRL_VEH_TYPE_CD": str,
    "UNIT_NUM": float,
}

vehicle_cols = [
    "CRN",
    "CRASH_YEAR",
    "COUNTY",
    "AVOID_MAN_CD",
    "BODY_TYPE",
    "COMM_VEH",
    "DAMAGE_IND",
    "DVR_PRES_IND",
    "EMERG_VEH_USE_CD",
    "GRADE",
    "HAZMAT_IND",
    "IMPACT_POINT",
    "INS_IND",
    "MAKE_CD",
    "MODEL_YR",
    "NM_AT_INTERSECTION",
    "NM_CROSSING_TCD",
    "NM_DISTRACTION",
    "NM_IN_CROSSWALK",
    "NM_LIGHTING",
    "NM_POWERED",
    "NM_REFLECT",
    "NON_MOTORIST",
    "OWNER_DRIVER",
    "PARTIAL_VIN",
    "PEOPLE_IN_UNIT",
    "PRIN_IMP_PT",
    "RDWY_ALIGNMENT",
    "SPECIAL_USAGE",
    "TOW_IND",
    "TRAVEL_DIRECTION",
    "TRAVEL_SPD",
    "TRL_VEH_CNT",
    "UNDER_RIDE_IND",
    "UNIT_NUM",
    "UNIT_TYPE",
    "VEH_COLOR_CD",
    "VEH_MOVEMENT",
    "VEH_POSITION",
    "VEH_REG_STATE",
    "VEH_ROLE",
    "VEH_TYPE",
    "VINA_BODY_TYPE_CD",
]

vehicle_dict = {
    "CRN": int,
    "CRASH_YEAR": str,
    "COUNTY": str,
    "AVOID_MAN_CD": str,
    "BODY_TYPE": str,
    "COMM_VEH": str,
    "DAMAGE_IND": str,
    "DVR_PRES_IND": str,
    "EMERG_VEH_USE_CD": str,
    "GRADE": str,
    "HAZMAT_IND": str,
    "IMPACT_POINT": str,
    "INS_IND": str,
    "MAKE_CD": str,
    "MODEL_YR": str,
    "NM_AT_INTERSECTION": str,
    "NM_CROSSING_TCD": str,
    "NM_DISTRACTION": str,
    "NM_IN_CROSSWALK": str,
    "NM_LIGHTING": str,
    "NM_POWERED": str,
    "NM_REFLECT": str,
    "NON_MOTORIST": str,
    "OWNER_DRIVER": str,
    "PARTIAL_VIN": str,
    "PEOPLE_IN_UNIT": float,
    "PRIN_IMP_PT": str,
    "RDWY_ALIGNMENT": str,
    "SPECIAL_USAGE": str,
    "TOW_IND": str,
    "TRAVEL_DIRECTION": str,
    "TRAVEL_SPD": str,
    "TRL_VEH_CNT": str,
    "UNDER_RIDE_IND": str,
    "UNIT_NUM": float,
    "UNIT_TYPE": str,
    "VEH_COLOR_CD": str,
    "VEH_MOVEMENT": str,
    "VEH_POSITION": str,
    "VEH_REG_STATE": str,
    "VEH_ROLE": str,
    "VEH_TYPE": str,
    "VINA_BODY_TYPE_CD": str,
}
